name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    name: Test on nodejs v.${{ matrix.node }}
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        node: [ 10, 12, 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
