name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
